-- 1. 표준 COALESCE
SELECT ANIMAL_TYPE,
    COALESCE(NAME, 'No name'),
    SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;
-- 2. 비표준 IFNULL (MYSQL 전용)
SELECT ANIMAL_TYPE,
    IFNULL(NAME, 'No name'),
    SEX_UPON_INTAKE
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;