-- CTE 를 활용한 방법
-- 0 ~ 23 까지 들어있는 테이블을 생성
WITH RECURSIVE HS as ( 
    SELECT 0 as n 
    UNION ALL
    SELECT n+1 
    FROM HS 
    WHERE n < 23
)

SELECT HS.N, COUNT(Ao.DATETIME)
FROM HS
LEFT JOIN ANIMAL_OUTS as Ao ON HOUR(Ao.DATETIME) = HS.N
GROUP BY HS.N;
